version: 2.1

steps: &steps_spec
  - checkout
  - run:
      name: Installing ruby dependencies
      command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
  - run:
      command: bundle exec rake
  - when:
      condition: << parameters.benchmark >>
      steps:
        - run:
            command: bundle exec rake benchmarks

jobs:
  ruby-2_2:
    parameters:
      benchmark:
        type: boolean
        default: false
    steps: *steps_spec
    docker:
      - image: ruby:2.2
  ruby-2_3:
    parameters:
      benchmark:
        type: boolean
        default: true
    steps: *steps_spec
    docker:
      - image: ruby:2.3
  ruby-2_4:
    parameters:
      benchmark:
        type: boolean
        default: true
    steps: *steps_spec
    docker:
      - image: ruby:2.4
  ruby-2_5:
    parameters:
      benchmark:
        type: boolean
        default: true
    steps: *steps_spec
    docker:
      - image: ruby:2.5
  ruby-2_6:
    parameters:
      benchmark:
        type: boolean
        default: true
    steps: *steps_spec
    docker:
      - image: ruby:2.6
  ruby-2_7:
    parameters:
      benchmark:
        type: boolean
        default: true
    steps: *steps_spec
    docker:
      - image: ruby:2.7
  ruby-3_0:
    parameters:
      benchmark:
        type: boolean
        default: true
    steps: *steps_spec
    docker:
      - image: ruby:3.0
  ruby-3_1:
    parameters:
      benchmark:
        type: boolean
        default: true
    steps: *steps_spec
    docker:
      - image: ruby:3.1
  ruby-3_2:
    parameters:
      benchmark:
        type: boolean
        default: true
    steps: *steps_spec
    docker:
      - image: ruby:3.2
  release-gem:
    steps:
      - checkout
      - run:
          name: Installing ruby dependencies
          command: bundle check --path=vendor/bundle || bundle install --path=vendor/bundle
      - run:
          name: Sign in to Github as CircleCI Bot
          command: |
            git config --global user.email "$CIRCLECI_GIT_BOT_GIT_EMAIL"
            git config --global user.name "$CIRCLECI_GIT_BOT_NAME"
      - run:
          name: Auth RubyGems
          command: |
            mkdir ~/.gem
            install -m 0600 /dev/null ~/.gem/credentials
            echo -e "---\n:rubygems_api_key: $RUBY_GEMS_API_KEY" > ~/.gem/credentials
      - deploy:
          name: Release New Gem Version
          command: |
            GEM_VERSION=$(ruby -r "./lib/blueprinter/version.rb" -e "puts Blueprinter::VERSION")
            echo "Attempting to release version '$GEM_VERSION' of Blueprinter..."
            bundle exec rake release || true # Don't fail when deploy does not take place
    docker:
      - image: ruby:2.5

workflows:
  version: 2
  test:
    jobs:
      - ruby-2_2
      - ruby-2_3
      - ruby-2_4
      - ruby-2_5
      - ruby-2_6
      - ruby-2_7
      - ruby-3_0
      - ruby-3_1
      - ruby-3_2
  release:
    jobs:
      - release-gem:
          filters:
            branches:
              only:
                - master
