name: 🐞 Bug
description: File a bug/issue
title: "[bug] <title>"
labels: [bug, needs-triage]
body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true
- type: checkboxes
  attributes:
    label: Is this a regression?
    description: Did this behavior work before?
    options:
    - label: Yes, this used to work before
      required: false
- type: textarea
  attributes:
    label: Current Behavior
    description: A concise description of what you're experiencing.
  validations:
    required: false
- type: textarea
  attributes:
    label: Expected Behavior
    description: A concise description of what you expected to happen.
  validations:
    required: false
- type: textarea
  attributes:
    label: Steps To Reproduce
    description: Steps to reproduce the behavior.
    placeholder: |
      1.
      2.
      3.
      4.
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment
    description: |
      examples:
        - **OS**: OSX 13.3.1
        - **Browser Name and Version**: Chrome Version 112.0.5615.49 (Official Build) (arm64)
        - **Ruby Version**: 3.0.0
    value: |
        - OS:
        - Browser Name and version:
        - Ruby Version:
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
