name: 'Auto Author Assign'
on:
  pull_request_target:
    types: [opened, reopened]
jobs:
  assign-author:
    runs-on: ubuntu-latest
    steps:
      - uses: toshimaru/auto-author-assign@3e19bfc990cb1cf0589dce95e9f75289bb1e22de # v3.0.3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
